using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using HQSOFT.Common.Permissions;
using HQSOFT.Common.Comments;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using HQSOFT.Common.Shared;

namespace HQSOFT.Common.Comments
{
    public class CommentsAppService : CommentsAppServiceBase, ICommentsAppService
    {
        //<suite-custom-code-autogenerated>
        public CommentsAppService(ICommentRepository commentRepository, CommentManager commentManager, IDistributedCache<CommentExcelDownloadTokenCacheItem, string> excelDownloadTokenCache)
            : base(commentRepository, commentManager, excelDownloadTokenCache)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}