using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace HQSOFT.Common.Comments
{
    public class CommentManager : CommentManagerBase
    {
        //<suite-custom-code-autogenerated>
        public CommentManager(ICommentRepository commentRepository)
            : base(commentRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}