using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;

using Volo.Abp;

namespace HQSOFT.Common.Comments
{
    public class Comment : CommentBase
    {
        //<suite-custom-code-autogenerated>
        protected Comment()
        {

        }

        public Comment(Guid id, Guid fromUserId, Guid docId, string? content = null, string? url = null)
            : base(id, fromUserId, docId, content, url)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}