using HQSOFT.Common.Notifications;
using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;

using Volo.Abp;

namespace HQSOFT.Common.Notifications
{
    public class Notification : NotificationBase
    {
        //<suite-custom-code-autogenerated>
        protected Notification()
        {

        }

        public Notification(Guid id, Guid fromUserId, Guid toUserId, string notiTitle, bool isRead, Guid docId, string url, NotificationsType type, string? notiBody = null)
            : base(id, fromUserId, toUserId, notiTitle, isRead, docId, url, type, notiBody)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}