using HQSOFT.Common.Notifications;
using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace HQSOFT.Common.Notifications
{
    public class NotificationManager : NotificationManagerBase
    {
        //<suite-custom-code-autogenerated>
        public NotificationManager(INotificationRepository notificationRepository)
            : base(notificationRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}